[package]
name = "grass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
http = "0.2.6"
ring = "0.16.20"
serde = "1.0.136"
serde_json = "1.0.79"
thiserror = "1.0.30"
url = "2.2.2"
